import { NewsNotification, NewsType, PlatformType } from "./news-notifications.interface";

export const NEWS_LIST: NewsNotification[] = [
  {
    id: 6,
    createdAt: "2022-01-06T00:00:00.000Z",
    type: NewsType.News,
    platforms: [PlatformType.Extension, PlatformType.Mobile],
    language: 'en-US',
    title: "Temple Wallet News #6",
    description: "First news",
    content: "First news lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quidem.",
    extensionImageUrl: "https://pbs.twimg.com/profile_images/1364551906283110400/4Ts3YPJz_400x400.jpg",
    mobileImageUrl: "https://pbs.twimg.com/profile_images/1364551906283110400/4Ts3YPJz_400x400.jpg",
    readInOriginalUrl: 'https://templewallet.com/',
  },
  {
    id: 5,
    createdAt: "2022-01-05T00:00:00.000Z",
    type: NewsType.News,
    platforms: [PlatformType.Extension],
    language: 'en-US',
    title: "Temple Wallet News #5",
    description: "Second news",
    content: "Second news lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quidem.",
    extensionImageUrl: "https://mj-gallery.com/ce5347a1-000e-4d77-8703-aef971c835ee/grid_0.png",
    mobileImageUrl: "https://mj-gallery.com/ce5347a1-000e-4d77-8703-aef971c835ee/grid_0.png",
    readInOriginalUrl: 'https://templewallet.com/',
  },
  {
    id: 4,
    createdAt: "2022-01-04T00:00:00.000Z",
    type: NewsType.ApplicationUpdate,
    platforms: [PlatformType.Mobile],
    language: 'en-US',
    title: "Temple Wallet ApplicationUpdate #4",
    description: "Very important update",
    content: "Very important update lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quidem.",
    extensionImageUrl: "https://assets.objkt.media/file/assets-003/QmbatSRJHqPzbvVLAxQkQFeHumWdiSSXSTY4VxBbawwJxb/artifact",
    mobileImageUrl: "https://assets.objkt.media/file/assets-003/QmbatSRJHqPzbvVLAxQkQFeHumWdiSSXSTY4VxBbawwJxb/artifact",
    readInOriginalUrl: 'https://templewallet.com/',
  },
  {
    id: 3,
    createdAt: "2022-01-03T00:00:00.000Z",
    type: NewsType.ApplicationUpdate,
    platforms: [PlatformType.Extension, PlatformType.Mobile],
    language: 'en-US',
    title: "Temple Wallet ApplicationUpdate #3",
    description: "Very important unread update",
    content: "Very important unread update lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quidem.",
    extensionImageUrl: "https://mj-gallery.com/8c84ef87-eaec-42e8-9e58-7e4ca530030e/grid_0.png",
    mobileImageUrl: "https://mj-gallery.com/8c84ef87-eaec-42e8-9e58-7e4ca530030e/grid_0.png",
    readInOriginalUrl: 'https://templewallet.com/',
  },
  {
    id: 2,
    createdAt: "2022-01-02T00:00:00.000Z",
    type: NewsType.Alert,
    platforms: [PlatformType.Extension],
    language: 'en-US',
    title: "Temple Wallet Alert #2",
    description: "Very important unread alert",
    content: "Very important unread alert lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quidem.",
    extensionImageUrl: "https://mj-gallery.com/119d8b55-41b6-49fb-bfd2-5e6e46355363/grid_0.png",
    mobileImageUrl: "https://mj-gallery.com/119d8b55-41b6-49fb-bfd2-5e6e46355363/grid_0.png",
    readInOriginalUrl: 'https://templewallet.com/',
  },
  {
    id: 1,
    createdAt: "2022-01-01T00:00:00.000Z",
    type: NewsType.Alert,
    platforms: [PlatformType.Mobile],
    language: 'en-US',
    title: "Temple Wallet Alert #1",
    description: "Very important alert readed",
    content: "Very important alert readed lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quidem.",
    extensionImageUrl: "https://mj-gallery.com/876c08c5-3ead-4fd8-99ba-215812e03885/grid_0.png",
    mobileImageUrl: "https://mj-gallery.com/876c08c5-3ead-4fd8-99ba-215812e03885/grid_0.png",
    readInOriginalUrl: 'https://templewallet.com/',
  }
]

export const WELCOME_NOTIFICATIONS_LIST: Array<NewsNotification> = [
  {
    id: 0,
    createdAt: "2020-01-01T00:00:00.000Z",
    type: NewsType.News,
    platforms: [PlatformType.Extension, PlatformType.Mobile],
    language: 'en-US',
    title: "Temple Wallet Greetings #0",
    description: "Welcome message",
    content: "Some welcome message lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quidem.",
    extensionImageUrl: "https://pbs.twimg.com/profile_images/1364551906283110400/4Ts3YPJz_400x400.jpg",
    mobileImageUrl: "https://pbs.twimg.com/profile_images/1364551906283110400/4Ts3YPJz_400x400.jpg",
    readInOriginalUrl: 'https://templewallet.com/',
  }
]
